name: AWS Lambda CICD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AccessKey }}
          aws-secret-access-key: ${{ secrets.SecretAccessKey }}
          aws-region: ap-south-1
      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name testClass --runtime java17 --handler testLiqui.testClass::handleRequest --role arn:aws:iam::730335235156:role/lamdaTest1 --zip-file fileb://target/testLiqui-0.0.1-SNAPSHOT.jar
        continue-on-error: true
      - name: Update Lambda Function
        run: aws lambda update-function-code --function-name testClass --zip-file fileb://target/testLiqui-0.0.1-SNAPSHOT.jar
